items:
  - luftballons: 0
  - pflaster: 0
  - bad_schrank_schluessel: 0
  - gel: 0
  - rote_farbe: 0
  - parfum: 0
  - milch: 0
  - handtuch: 0
  - ring: 0
  - anzug: 0
  - wein: 0
  - buch: 0
  - kaninchen: 0
  - giesskanne: 0
  - stift: 0
  - spitzer_stift: 0
  - besen: 0
  - lappen: 0
  - saft: 0
  - mayo: 0
  - hotsauce: 0
state_vars:
  - abgesetzt: 0
  - hingelegt: 0
  - wunde_gesehen: 0
  - baby_abgelegt: 0
  - baby_nicht_in_wohnzimmer_bemerkt: 0
  - baby_in_garage_gefunden: 0
  - katzenklappe_entdeckt: 0
  - gel_benutzt: 0
  - gel_idee: 0
  - leiter_benutzt: 0
  - leiter_verschoben: 0
  - farbe_fuettern: 0
  - parfum_fuettern: 0
  - leim_gefuettert: 0
  - baby_klebt_an_flasche: 0
  - spur_gefunden: 0
  - spur_gefolgt: 0
  - wasserhahn_aufgedreht: 0
  - wasserhahn_heiss_aufgedreht: 0
  - wasserhahn_kalt_aufgedreht: 0
  - handtuch_benutzt: 0
  - buerste_benutzt: 0
  - pfarrer_bewusstlos: 0
  - pfarrer_bewusstlos_bad: 0
  - pfarrer_licht_aus: 0
  - treppenhaus_sauber: 0
  - rechnung_unterschrieben: 0
  - realization: 0
  - papierschredder_an: 0
  - wasserhahn_haus_aufgedreht: 0
  - giesskanne_voll: 0
  - lappen_nass: 0
  - kueche_richtiger_code: 0
initial_screen: start