items:
  - luftballons: 0
  - pflaster: 0
  - bad_schrank_schluessel: 0
  - gel: 0
  - leiter: 0
  - rote_farbe: 0
  - parfum: 0
  - milch: 0
  - handtuch: 0
  - ring: 0
  - anzug: 0
state_vars:
  - wunde_gesehen: 0
  - baby_abgelegt: 0
  - baby_nicht_in_wohnzimmer_bemerkt: 0
  - katzenklappe_entdeckt: 0
  - gel_benutzt: 0
  - gel_idee: 0
  - leiter_benutzt: 0
  - farbe_fuettern: 0
  - parfum_fuettern: 0
  - leim_gefuettert: 0
  - baby_klebt_an_flasche: 0
  - spur_gefunden: 0
  - spur_gefolgt: 0
  - wasserhahn_aufgedreht: 0
  - wasserhahn_heiss_aufgedreht: 0
  - wasserhahn_kalt_aufgedreht: 0
  - handtuch_benutzt: 0
initial_screen: start